function Start-TheDashboard {
    <#
    .SYNOPSIS
    Generates TheDashboard from multiple provided reports in form of HTML files.

    .DESCRIPTION
    Generates TheDashboard from multiple provided reports in form of HTML files.
    It also generates statistics and charts based on the data provided by additional data.

    .PARAMETER Elements
    ScriptBlock that accepts New-Dashboard* functions, allowing for configuration of TheDashboard.

    .PARAMETER HTMLPath
    Path to HTML files that will be generated.

    .PARAMETER StatisticsPath
    Path to XML file that will save some of the data that is used to generate charts

    .PARAMETER Logo
    Path to logo that will be used in the header.

    .PARAMETER Folders
    Folders that will be used to generate TheDashboard.
    Can co-exist with Elements parameter, and configuration using both will be merged.

    .PARAMETER UrlPath
    URL that will be used as a starting point for TheDashboard, and used by all the links.
    By default the URL uses relative path, but it can be changed to absolute path.
    This is useful for example when you want to use TheDashboard on a SharePoint site, where the files are stored in a different place.

    .PARAMETER Replacements
    Replacements that will be used to replace names within TheDashboard.

    .PARAMETER RemoveNotIncluded
    Removes files that are not included in the menu.
    This is useful to clean up files that are not displayed, but be careful during testing.

    .PARAMETER DeleteMethod
    Specifies how files are removed when they are not included in the menu.
    By default, files are moved to the Recycle Bin.
    All options are: RemoveItem, DotNetDelete, RecycleBin.

    .PARAMETER TestMode
    Pretends to generate TheDashboard, but does not actually generate it.
    Other processes are executed, but no HTML files are created.
    This is useful for testing along with PassThru parameter, which will return all the data that would be used to generate TheDashboard.

    .PARAMETER ShowHTML
    Show TheDashboard in browser after generating it.

    .PARAMETER Online
    Tells Dashboard to use CSS/JS from CDN instead of local files.

    .PARAMETER PassThru
    Returns the object that was generated by the script.

    .EXAMPLE
    An example

    .NOTES
    General notes
    #>
    [cmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Position = 0)][ScriptBlock] $Elements,
        [Parameter(Position = 1, Mandatory)][alias('FilePath')][string] $HTMLPath,
        [string] $StatisticsPath,
        [string] $Logo,
        [System.Collections.IDictionary] $Folders,
        [System.Collections.IDictionary] $Replacements,
        [switch] $RemoveNotIncluded,
        [ValidateSet("RemoveItem", "DotNetDelete", "RecycleBin")]
        [string] $DeleteMethod = "RecycleBin",
        [Uri] $UrlPath,
        [switch] $ShowHTML,
        [switch] $Online,
        [switch] $PassThru,
        [switch] $TestMode
    )
    $Script:Reporting = [ordered] @{}
    $Script:Reporting['Version'] = Get-GitHubVersion -Cmdlet 'Start-TheDashboard' -RepositoryOwner 'evotecit' -RepositoryName 'TheDashboard'

    Write-Color '[i]', "[TheDashboard] ", 'Version', ' [Informative] ', $Script:Reporting['Version'] -Color Yellow, DarkGray, Yellow, DarkGray, Magenta

    if ($TestMode) {
        Write-Color -Text '[i]', "[TheDashboard] ", 'TestMode enabled', ' [Informative] ' -Color Yellow, DarkGray, Yellow, DarkGray, Magenta
        $WhatIfPreference = $true
    }
    if (-not $Folders) {
        $Folders = [ordered] @{}
    }
    $GageConfiguration = [System.Collections.Generic.List[System.Collections.IDictionary]]::new()
    $FoldersConfiguration = [System.Collections.Generic.List[System.Collections.IDictionary]]::new()
    $ReplacementConfiguration = [System.Collections.Generic.List[System.Collections.IDictionary]]::new()
    $FolderLimit = [ordered] @{}

    $convertNestedElementsSplat = @{
        Elements                 = $Elements
        GageConfiguration        = $GageConfiguration
        FoldersConfiguration     = $FoldersConfiguration
        ReplacementConfiguration = $ReplacementConfiguration
        FolderLimit              = $FolderLimit
    }

    Convert-NestedElements @convertNestedElementsSplat

    $Extension = [io.path]::GetExtension($HTMLPath)
    $FolderPath = [io.path]::GetDirectoryName($HTMLPath)

    $TopStats = Import-DashboardStatistics -StatisticsPath $StatisticsPath

    # convert replacements into a single entry
    # this is to make sure user can use different ways of replacing things
    $Replacements = Convert-MultipleReplacements -Replacements $Replacements -ReplacementConfiguration $ReplacementConfiguration

    # build folders configuration
    Set-FolderConfiguration -Folders $Folders -FoldersConfiguration $FoldersConfiguration -FolderLimit $FolderLimit

    # copy or move HTML files to the right place, as user requested
    Copy-HTMLFiles -Folders $Folders -Extension $Extension

    # create menu data information based on files
    $Files = Convert-FilesToMenuData -Folders $Folders -Replacements $Replacements -Extension $Extension

    # Prepare menu based on files
    $MenuBuilder = Convert-FilesToMenu -Files $Files -Folders $Folders

    $FilePathsGenerated = New-HTMLReport -OutputElements $GageConfiguration -Logo $Logo -MenuBuilder $MenuBuilder -Configuration $Configuration -TopStats $TopStats -Files $Files -ShowHTML:$ShowHTML.IsPresent -HTMLPath $HTMLPath -Online:$Online.IsPresent -Force:$Force.IsPresent -Extension $Extension -UrlPath $UrlPath -Pretend:$TestMode.IsPresent
    Remove-DiscardedReports -FilePathsGenerated $FilePathsGenerated -FolderPath $FolderPath -Extension $Extension

    # Export statistics to file to create charts later on
    if ($StatisticsPath) {
        try {
            $TopStats | Export-Clixml -Depth 3 -LiteralPath $StatisticsPath -ErrorAction Stop -WhatIf:$false
        } catch {
            Write-Color -Text '[e]', "[TheDashboard] ", 'Failed to export statistics', ' [Error] ', $_.Exception.Message -Color Yellow, DarkGray, Yellow, DarkGray, Red
        }
    }
    Write-Color -Text '[i]', "[TheDashboard] ", 'Done', ' [Informative] ' -Color Yellow, DarkGray, Yellow, DarkGray, Magenta

    $FilesToKeepOrRemove = Convert-FilesToKeepOrRemove -FilePathsGenerated $FilePathsGenerated -Files $Files -DeleteMethod $DeleteMethod -RemoveNotIncluded:$RemoveNotIncluded.IsPresent -WhatIf:$WhatIfPreference

    if ($PassThru) {
        [ordered] @{
            FilesToKeepOrRemove = $FilesToKeepOrRemove
            Folders             = $Folders
            Extension           = $Extension
            Files               = $Files
            MenuBuilder         = $MenuBuilder
            TopStats            = $TopStats
            StatisticsPath      = $StatisticsPath
            Replacements        = $Replacements
            FilePathsGenerated  = $FilePathsGenerated
        }
    }
}